#################### ROUND 50: ravilla (W) vs seokjooy (B): game 1 ####################
##### game start! #####
INPUT for seokjooy:
GAME
BLACK
300
.b.b.b.b
b.b.b.b.
.b.b.b.b
........
........
w.w.w.w.
.w.w.w.w
w.w.w.w.
##### Running: /usr/bin/time -o time_50_ravilla_seokjooy.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on seokjooy #####
child exited with value 1
##### ERROR: /usr/bin/time -o time_50_ravilla_seokjooy.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on seokjooy #####
##### Output of failed program (stdout + stderr): #####
Traceback (most recent call last):
  File "homework.py", line 472, in <module>
    player_1 = Agent()
  File "homework.py", line 31, in __init__
    self.start_time = time.clock()
AttributeError: module 'time' has no attribute 'clock'
##### End of output of failed program #####
##### seokjooy plays [No Move] in 0.212256193161011s #####
##### No output.txt found. Making a bogus one... #####
##### Running: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_50_ravilla_seokjooy #####
Step in a move needs to have 3 sections, found 1 in 'illegal'.
child exited with value 255
##### ERROR: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_50_ravilla_seokjooy #####
Game server reported error. Assuming bogus move.
##### GAME OVER: seokjooy loses because of illegal move [No Move] #####
Server said: FAIL
########## ROUND 50 GAMESCORE AFTER GAME 1: ravilla=1 and seokjooy=0 ##########
#################### ROUND 50: ravilla (B) vs seokjooy (W): game 2 ####################
##### game start! #####
INPUT for ravilla:
GAME
BLACK
300
.b.b.b.b
b.b.b.b.
.b.b.b.b
........
........
w.w.w.w.
.w.w.w.w
w.w.w.w.
##### Running: /usr/bin/time -o time_50_ravilla_seokjooy.txt -f "%U" ./homework > stulog.txt 2>&1 on ravilla #####
##### SUCCESS: /usr/bin/time -o time_50_ravilla_seokjooy.txt -f "%U" ./homework > stulog.txt 2>&1 on ravilla #####
##### ravilla plays [E b6 a5] in 0.0152318477630615s #####
##### Running: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_50_ravilla_seokjooy #####
Move is valid
Couldn't read file 'current_ply.txt'
Couldn't read content from file 'current_ply.txt'
Couldn't read file 'lastmatchange_ply.txt'
Couldn't read content from file 'lastmatchange_ply.txt'
##### SUCCESS: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_50_ravilla_seokjooy #####
INPUT for seokjooy:
GAME
WHITE
300
.b.b.b.b
b.b.b.b.
...b.b.b
b.......
........
w.w.w.w.
.w.w.w.w
w.w.w.w.
##### Running: /usr/bin/time -o time_50_ravilla_seokjooy.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on seokjooy #####
child exited with value 1
##### ERROR: /usr/bin/time -o time_50_ravilla_seokjooy.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on seokjooy #####
##### Output of failed program (stdout + stderr): #####
Traceback (most recent call last):
  File "homework.py", line 472, in <module>
    player_1 = Agent()
  File "homework.py", line 31, in __init__
    self.start_time = time.clock()
AttributeError: module 'time' has no attribute 'clock'
##### End of output of failed program #####
##### seokjooy plays [No Move] in 0.223877906799316s #####
##### No output.txt found. Making a bogus one... #####
##### Running: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_50_ravilla_seokjooy #####
Step in a move needs to have 3 sections, found 1 in 'illegal'.
child exited with value 255
##### ERROR: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_50_ravilla_seokjooy #####
Game server reported error. Assuming bogus move.
##### GAME OVER: seokjooy loses because of illegal move [No Move] #####
Server said: FAIL
########## ROUND 50 GAMESCORE AFTER GAME 2: ravilla=2 and seokjooy=0 ##########
#################### ROUND 50: ravilla (W) vs seokjooy (B): game 3 ####################
##### game start! #####
INPUT for seokjooy:
GAME
BLACK
300
.b.b.b.b
b.b.b.b.
.b.b.b.b
........
........
w.w.w.w.
.w.w.w.w
w.w.w.w.
##### Running: /usr/bin/time -o time_50_ravilla_seokjooy.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on seokjooy #####
child exited with value 1
##### ERROR: /usr/bin/time -o time_50_ravilla_seokjooy.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on seokjooy #####
##### Output of failed program (stdout + stderr): #####
Traceback (most recent call last):
  File "homework.py", line 472, in <module>
    player_1 = Agent()
  File "homework.py", line 31, in __init__
    self.start_time = time.clock()
AttributeError: module 'time' has no attribute 'clock'
##### End of output of failed program #####
##### seokjooy plays [No Move] in 0.222681999206543s #####
##### No output.txt found. Making a bogus one... #####
##### Running: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_50_ravilla_seokjooy #####
Step in a move needs to have 3 sections, found 1 in 'illegal'.
child exited with value 255
##### ERROR: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_50_ravilla_seokjooy #####
Game server reported error. Assuming bogus move.
##### GAME OVER: seokjooy loses because of illegal move [No Move] #####
Server said: FAIL
########## ROUND 50 GAMESCORE AFTER GAME 3: ravilla=3 and seokjooy=0 ##########
#################### ROUND 50: ravilla (B) vs seokjooy (W): game 4 ####################
##### game start! #####
INPUT for ravilla:
GAME
BLACK
300
.b.b.b.b
b.b.b.b.
.b.b.b.b
........
........
w.w.w.w.
.w.w.w.w
w.w.w.w.
##### Running: /usr/bin/time -o time_50_ravilla_seokjooy.txt -f "%U" ./homework > stulog.txt 2>&1 on ravilla #####
##### SUCCESS: /usr/bin/time -o time_50_ravilla_seokjooy.txt -f "%U" ./homework > stulog.txt 2>&1 on ravilla #####
##### ravilla plays [E b6 a5] in 0.0151691436767578s #####
##### Running: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_50_ravilla_seokjooy #####
Move is valid
Couldn't read file 'current_ply.txt'
Couldn't read content from file 'current_ply.txt'
Couldn't read file 'lastmatchange_ply.txt'
Couldn't read content from file 'lastmatchange_ply.txt'
##### SUCCESS: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_50_ravilla_seokjooy #####
INPUT for seokjooy:
GAME
WHITE
300
.b.b.b.b
b.b.b.b.
...b.b.b
b.......
........
w.w.w.w.
.w.w.w.w
w.w.w.w.
##### Running: /usr/bin/time -o time_50_ravilla_seokjooy.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on seokjooy #####
child exited with value 1
##### ERROR: /usr/bin/time -o time_50_ravilla_seokjooy.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on seokjooy #####
##### Output of failed program (stdout + stderr): #####
Traceback (most recent call last):
  File "homework.py", line 472, in <module>
    player_1 = Agent()
  File "homework.py", line 31, in __init__
    self.start_time = time.clock()
AttributeError: module 'time' has no attribute 'clock'
##### End of output of failed program #####
##### seokjooy plays [No Move] in 0.216182947158813s #####
##### No output.txt found. Making a bogus one... #####
##### Running: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_50_ravilla_seokjooy #####
Step in a move needs to have 3 sections, found 1 in 'illegal'.
child exited with value 255
##### ERROR: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_50_ravilla_seokjooy #####
Game server reported error. Assuming bogus move.
##### GAME OVER: seokjooy loses because of illegal move [No Move] #####
Server said: FAIL
########## ROUND 50 GAMESCORE AFTER GAME 4: ravilla=4 and seokjooy=0 ##########


########## GRAND WINNER ROUND 50 IS ravilla BY 4 vs 0 GAMESCORE ##########
