#################### ROUND 2: samana (B) vs wanrongz (W): game 1 ####################
##### game start! #####
INPUT for samana:
GAME
BLACK
300
.b.b.b.b
b.b.b.b.
.b.b.b.b
........
........
w.w.w.w.
.w.w.w.w
w.w.w.w.
##### Running: /usr/bin/time -o time_2_samana_wanrongz.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on samana #####
child exited with value 1
##### ERROR: /usr/bin/time -o time_2_samana_wanrongz.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on samana #####
##### Output of failed program (stdout + stderr): #####
Traceback (most recent call last):
  File "homework.py", line 557, in <module>
    main_start_time =time.clock() #process_time()
AttributeError: module 'time' has no attribute 'clock'
##### End of output of failed program #####
##### samana plays [No Move] in 0.625814914703369s #####
##### No output.txt found. Making a bogus one... #####
##### Running: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_2_samana_wanrongz #####
Step in a move needs to have 3 sections, found 1 in 'illegal'.
child exited with value 255
##### ERROR: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_2_samana_wanrongz #####
Game server reported error. Assuming bogus move.
##### GAME OVER: samana loses because of illegal move [No Move] #####
Server said: FAIL
########## ROUND 2 GAMESCORE AFTER GAME 1: samana=0 and wanrongz=1 ##########
#################### ROUND 2: samana (W) vs wanrongz (B): game 2 ####################
##### game start! #####
INPUT for wanrongz:
GAME
BLACK
300
.b.b.b.b
b.b.b.b.
.b.b.b.b
........
........
w.w.w.w.
.w.w.w.w
w.w.w.w.
##### Running: /usr/bin/time -o time_2_samana_wanrongz.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on wanrongz #####
##### SUCCESS: /usr/bin/time -o time_2_samana_wanrongz.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on wanrongz #####
##### wanrongz plays [E b6 c5] in 0.04s #####
##### Running: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_2_samana_wanrongz #####
Move is valid
Couldn't read file 'current_ply.txt'
Couldn't read content from file 'current_ply.txt'
Couldn't read file 'lastmatchange_ply.txt'
Couldn't read content from file 'lastmatchange_ply.txt'
##### SUCCESS: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_2_samana_wanrongz #####
INPUT for samana:
GAME
WHITE
300
.b.b.b.b
b.b.b.b.
...b.b.b
..b.....
........
w.w.w.w.
.w.w.w.w
w.w.w.w.
##### Running: /usr/bin/time -o time_2_samana_wanrongz.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on samana #####
child exited with value 1
##### ERROR: /usr/bin/time -o time_2_samana_wanrongz.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on samana #####
##### Output of failed program (stdout + stderr): #####
Traceback (most recent call last):
  File "homework.py", line 557, in <module>
    main_start_time =time.clock() #process_time()
AttributeError: module 'time' has no attribute 'clock'
##### End of output of failed program #####
##### samana plays [No Move] in 0.783799886703491s #####
##### No output.txt found. Making a bogus one... #####
##### Running: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_2_samana_wanrongz #####
Step in a move needs to have 3 sections, found 1 in 'illegal'.
child exited with value 255
##### ERROR: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_2_samana_wanrongz #####
Game server reported error. Assuming bogus move.
##### GAME OVER: samana loses because of illegal move [No Move] #####
Server said: FAIL
########## ROUND 2 GAMESCORE AFTER GAME 2: samana=0 and wanrongz=2 ##########
#################### ROUND 2: samana (B) vs wanrongz (W): game 3 ####################
##### game start! #####
INPUT for samana:
GAME
BLACK
300
.b.b.b.b
b.b.b.b.
.b.b.b.b
........
........
w.w.w.w.
.w.w.w.w
w.w.w.w.
##### Running: /usr/bin/time -o time_2_samana_wanrongz.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on samana #####
child exited with value 1
##### ERROR: /usr/bin/time -o time_2_samana_wanrongz.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on samana #####
##### Output of failed program (stdout + stderr): #####
Traceback (most recent call last):
  File "homework.py", line 557, in <module>
    main_start_time =time.clock() #process_time()
AttributeError: module 'time' has no attribute 'clock'
##### End of output of failed program #####
##### samana plays [No Move] in 0.773428201675415s #####
##### No output.txt found. Making a bogus one... #####
##### Running: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_2_samana_wanrongz #####
Step in a move needs to have 3 sections, found 1 in 'illegal'.
child exited with value 255
##### ERROR: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_2_samana_wanrongz #####
Game server reported error. Assuming bogus move.
##### GAME OVER: samana loses because of illegal move [No Move] #####
Server said: FAIL
########## ROUND 2 GAMESCORE AFTER GAME 3: samana=0 and wanrongz=3 ##########
#################### ROUND 2: samana (W) vs wanrongz (B): game 4 ####################
##### game start! #####
INPUT for wanrongz:
GAME
BLACK
300
.b.b.b.b
b.b.b.b.
.b.b.b.b
........
........
w.w.w.w.
.w.w.w.w
w.w.w.w.
##### Running: /usr/bin/time -o time_2_samana_wanrongz.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on wanrongz #####
##### SUCCESS: /usr/bin/time -o time_2_samana_wanrongz.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on wanrongz #####
##### wanrongz plays [E b6 c5] in 0.03s #####
##### Running: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_2_samana_wanrongz #####
Move is valid
Couldn't read file 'current_ply.txt'
Couldn't read content from file 'current_ply.txt'
Couldn't read file 'lastmatchange_ply.txt'
Couldn't read content from file 'lastmatchange_ply.txt'
##### SUCCESS: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_2_samana_wanrongz #####
INPUT for samana:
GAME
WHITE
300
.b.b.b.b
b.b.b.b.
...b.b.b
..b.....
........
w.w.w.w.
.w.w.w.w
w.w.w.w.
##### Running: /usr/bin/time -o time_2_samana_wanrongz.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on samana #####
child exited with value 1
##### ERROR: /usr/bin/time -o time_2_samana_wanrongz.txt -f "%U" python3 homework.py > stulog.txt 2>&1 on samana #####
##### Output of failed program (stdout + stderr): #####
Traceback (most recent call last):
  File "homework.py", line 557, in <module>
    main_start_time =time.clock() #process_time()
AttributeError: module 'time' has no attribute 'clock'
##### End of output of failed program #####
##### samana plays [No Move] in 0.66471004486084s #####
##### No output.txt found. Making a bogus one... #####
##### Running: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_2_samana_wanrongz #####
Step in a move needs to have 3 sections, found 1 in 'illegal'.
child exited with value 255
##### ERROR: /usr/lib/jvm/jdk-14.0.1/bin/java -jar /lab/itti/projects/checkers-competition/server/referee.jar on run_2_samana_wanrongz #####
Game server reported error. Assuming bogus move.
##### GAME OVER: samana loses because of illegal move [No Move] #####
Server said: FAIL
########## ROUND 2 GAMESCORE AFTER GAME 4: samana=0 and wanrongz=4 ##########


########## GRAND WINNER ROUND 2 IS wanrongz BY 4 vs 0 GAMESCORE ##########
